[package]
name = "sushi"
version = "0.1.0"
authors = []
edition = "2018"

[profile.release]
debug = true

[dependencies]
fastly = "^0.2.0-alpha1"
serde = "1.0.104"
serde_derive = "1.0.104"
serde_json = "1.0.48"